import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./navbar/page";
import Footer from "./footer";
import Landingpage from "./landingpage/page";
import { Quicksand } from 'next/font/google'

const quicksand = Quicksand({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
});
export const metadata: Metadata = {
  title: "Shiv ManPower Services",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
     <html lang="en">
      <body className={`${quicksand.className} antialiased font-sans min-h-screen flex flex-col`}>
        <Landingpage />
        <Navbar />
        <main className="flex-1">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
